<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PureX.Core</RootNamespace>
    <AssemblyName>PureX.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.10.2" />
  </ItemGroup>

</Project>
